#pragma once
// Auto-tuned FlashAttention block size (generated by scripts/autotune_flash.py)
#define FLASH_BLOCK_SIZE 128
#define FLASH_BLOCK_SIZE_KV 128
#define KV_CACHE_SOA_THRESHOLD 512
// Results: {32: 11.6796, 64: 11.311, 128: 11.2064, 256: 11.5109} best 128 (11.2064ms)
