#pragma once
// Auto-tuned FlashAttention block size (generated by scripts/autotune_flash.py)
#define FLASH_BLOCK_SIZE 32
#define FLASH_BLOCK_SIZE_KV 32
#define KV_CACHE_SOA_THRESHOLD 512
// Results: {32: 13.4132, 64: 16.575, 128: 32.1073, 256: 18.5341} best 32 (13.4132ms)
