#pragma once
// GEMM tile advisory (generated by scripts/autotune_flash.py).
// The numpy-cpp backend tiles internally; the USE_NUMPY_CPP=OFF naive path in
// src/tensor.cpp tiles its i/k/j loops with these values.
#define GEMM_BLOCK_M 64
#define GEMM_BLOCK_N 64
#define GEMM_BLOCK_K 64
// Anchor: {32: 11.6796, 64: 11.311, 128: 11.2064, 256: 11.5109} (matmul 128x128 landscape; best flash block 128)
