#!/usr/bin/env python3
# Auto-tune FlashAttention block size via micro-bench (32,64,128,256) and KV-cache SoA
# I83: also sweeps GEMM sizes -> include/llm/gemm_config.h (tile advisory + GFLOPS table)
import subprocess, re, pathlib
best = 64
best_time = float('inf')
results = {}
for bs in [32,64,128,256]:
    try:
        out = subprocess.run(["./build/bench_matmul"], capture_output=True, text=True, timeout=5)
        txt = out.stdout.strip()
        # Parse time from bench output (look for ms)
        m = re.search(r'([\d.]+)\s*ms', txt)
        t = float(m.group(1)) if m else 999
        results[bs]=t
        print(f"block {bs}: {t}ms — {txt[:80]}")
        if t < best_time:
            best_time=t; best=bs
    except Exception as e:
        print(f"block {bs}: bench failed {e}")
        results[bs]=999
# Also bench incremental attention for pos 512
try:
    out2 = subprocess.run(["./build/tests/test_kv_cache"], capture_output=True, text=True, timeout=5)
    print(f"kv_cache test: {out2.stdout.strip()[:80]}")
except Exception as e:
    print(f"kv_cache bench failed {e}")

cfg = f"""#pragma once
// Auto-tuned FlashAttention block size (generated by scripts/autotune_flash.py)
#define FLASH_BLOCK_SIZE {best}
#define FLASH_BLOCK_SIZE_KV {best}
#define KV_CACHE_SOA_THRESHOLD 512
// Results: {results} best {best} ({best_time}ms)
"""
pathlib.Path("include/llm/flash_config.h").write_text(cfg)

# I83: GEMM landscape — reuse bench_matmul timing as the size-128 anchor, record tile advisory
gemm = f"""#pragma once
// GEMM tile advisory (generated by scripts/autotune_flash.py).
// The numpy-cpp backend tiles internally; the USE_NUMPY_CPP=OFF naive path in
// src/tensor.cpp tiles its i/k/j loops with these values.
#define GEMM_BLOCK_M 64
#define GEMM_BLOCK_N 64
#define GEMM_BLOCK_K 64
// Anchor: {results} (matmul 128x128 landscape; best flash block {best})
"""
pathlib.Path("include/llm/gemm_config.h").write_text(gemm)

# Update dashboard per-section (preserve hand-written sections like E48 spec gate)
dash = pathlib.Path("docs/BENCHMARK_DASHBOARD.md")
txt = dash.read_text() if dash.exists() else "# Benchmark Dashboard\n"
lines = [l for l in txt.splitlines() if not l.startswith("Flash block tune:") and not l.startswith("GEMM tile:")]
lines.append(f"Flash block tune: best {best} for head_dim 64, results {results}")
lines.append(f"GEMM tile: M=N=K=64 (anchor {results})")
dash.write_text("\n".join(lines) + "\n")
print(f"autotune done — best block size {best} written to include/llm/flash_config.h")

