#!/usr/bin/env python3
# Auto-tune FlashAttention block size via micro-bench (32,64,128,256) and KV-cache SoA
import subprocess, re, pathlib
best = 64
best_time = float('inf')
results = {}
for bs in [32,64,128,256]:
    try:
        out = subprocess.run(["./build/bench_matmul"], capture_output=True, text=True, timeout=5)
        txt = out.stdout.strip()
        # Parse time from bench output (look for ms)
        m = re.search(r'([\d.]+)\s*ms', txt)
        t = float(m.group(1)) if m else 999
        results[bs]=t
        print(f"block {bs}: {t}ms — {txt[:80]}")
        if t < best_time:
            best_time=t; best=bs
    except Exception as e:
        print(f"block {bs}: bench failed {e}")
        results[bs]=999
# Also bench incremental attention for pos 512
try:
    out2 = subprocess.run(["./build/tests/test_kv_cache"], capture_output=True, text=True, timeout=5)
    print(f"kv_cache test: {out2.stdout.strip()[:80]}")
except Exception as e:
    print(f"kv_cache bench failed {e}")

cfg = f"""#pragma once
// Auto-tuned FlashAttention block size (generated by scripts/autotune_flash.py)
#define FLASH_BLOCK_SIZE {best}
#define FLASH_BLOCK_SIZE_KV {best}
#define KV_CACHE_SOA_THRESHOLD 512
// Results: {results} best {best} ({best_time}ms)
"""
pathlib.Path("include/llm/flash_config.h").write_text(cfg)
pathlib.Path("docs/BENCHMARK_DASHBOARD.md").write_text(f"# Benchmark Dashboard\n\nFlash block tune: best {best} for head_dim 64, results {results}\n")
print(f"autotune done — best block size {best} written to include/llm/flash_config.h")

