# J91: derive version from git describe at configure time.
# Output: <binary-dir>/generated/llm/version.h (shadows static fallback).
execute_process(
  COMMAND git describe --tags --always --dirty
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_DESCRIBE
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET)
if(NOT GIT_DESCRIBE)
  set(GIT_DESCRIBE "0.0.0+nogit")
endif()
# Parse vX.Y.Z prefix when present
set(VER_MAJOR 0)
set(VER_MINOR 4)
set(VER_PATCH 0)
if(GIT_DESCRIBE MATCHES "^v?([0-9]+)\\.([0-9]+)\\.([0-9]+)")
  set(VER_MAJOR ${CMAKE_MATCH_1})
  set(VER_MINOR ${CMAKE_MATCH_2})
  set(VER_PATCH ${CMAKE_MATCH_3})
endif()
file(WRITE ${CMAKE_BINARY_DIR}/generated/llm/version.h
  "#pragma once\n"
  "// Auto-generated by cmake/version.cmake — do not edit (J91).\n"
  "#define LLM_CPP_VERSION \"${GIT_DESCRIBE}\"\n"
  "#define LLM_CPP_VERSION_MAJOR ${VER_MAJOR}\n"
  "#define LLM_CPP_VERSION_MINOR ${VER_MINOR}\n"
  "#define LLM_CPP_VERSION_PATCH ${VER_PATCH}\n")
message(STATUS "llm-cpp version: ${GIT_DESCRIBE}")
